title: Eugene Zuev
description: My Resume
logo: https://media.istockphoto.com/vectors/hacker-logo-vector-id1056797982?k=20&m=1056797982&s=170667a&w=0&h=Tu2Qi1R7OeHOpJvwbRmiqu1_4NFQidYpnNSbv8JP6Zg=
theme: jekyll-theme-minimal
